[package]
name = "crontab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
ordinal = "0.3.2"
clap = { version = "4.4.8", features = ["derive"]}